make clean
make PROJECT_MODEL=_model_1 DEBUG="-DUART_PRINTF_MODE=OFF"
make PROJECT_MODEL=_model_2 DEBUG="-DUART_PRINTF_MODE=OFF"
make PROJECT_MODEL=_model_3 DEBUG="-DUART_PRINTF_MODE=OFF"
make PROJECT_MODEL=_model_4 DEBUG="-DUART_PRINTF_MODE=OFF"
