#ifndef SRC_ZCL_ZCL_CUSTOM_ATTR_H_
#define SRC_ZCL_ZCL_CUSTOM_ATTR_H_

#define ZCL_CUSTOM_ATTRID_SWITCH_TYPE           0xF000
#define ZCL_CUSTOM_ATTRID_DEVICE_MODEL          0xF002
#define ZCL_CUSTOM_ATTRID_SCENE_SCENE_ID        0xF000
#define ZCL_CUSTOM_ATTRID_SCENE_GROUP_ID        0xF001

enum {
    ZCL_CUSTOM_SWITCH_TYPE_LEVEL_MOVE = 0x03,
    ZCL_CUSTOM_SWITCH_TYPE_LEVEL_MOVE_UP,
    ZCL_CUSTOM_SWITCH_TYPE_LEVEL_MOVE_DOWN,
    ZCL_CUSTOM_SWITCH_TYPE_SCENE,
    ZCL_CUSTOM_SWITCH_TYPE_MAXNUM
};

#define DEFAULT_MOVE_RATE                       100

#endif /* SRC_ZCL_ZCL_CUSTOM_ATTR_H_ */
